// eslint-disable-next-line @typescript-eslint/no-extraneous-class
export default class Stats {
	public static getDefaults(): Record<PLAYER_STATS_TYPE_HELPER, number> {
		return {
			strength: 0,
			additionalStrength: 0,
			multiplierStrength: 1,
			dexterity: 0,
			additionalDexterity: 0,
			multiplierDexterity: 1,
			intelligence: 0,
			additionalIntelligence: 0,
			multiplierIntelligence: 1,
			life: 0,
			additionalLife: 0,
			multiplierLife: 1,
			mana: 0,
			additionalMana: 0,
			multiplierMana: 1,
			energyShield: 0,
			additionalEnergyShield: 0,
			multiplierEnergyShield: 1,
			armor: 0,
			additionalArmor: 0,
			multiplierArmor: 1,
			evasion: 0,
			additionalEvasion: 0,
			multiplierEvasion: 1,
			accuracy: 0,
			additionalAccuracy: 0,
			multiplierAccuracy: 1,
			physicalDamageMin: 1,
			additionalPhysicalDamageMin: 0,
			multiplierPhysicalDamageMin: 1,
			physicalDamageMax: 10,
			additionalPhysicalDamageMax: 0,
			multiplierPhysicalDamageMax: 1,
		};
	}
}

export const PLAYER_STATS = {
	STRENGTH: 'strength',
	ADDITIONAL_STRENGTH: 'additionalStrength',
	MULTIPLIER_STRENGTH: 'multiplierStrength',
	DEXTERITY: 'dexterity',
	ADDITIONAL_DEXTERITY: 'additionalDexterity',
	MULTIPLIER_DEXTERITY: 'multiplierDexterity',
	INTELLIGENCE: 'intelligence',
	ADDITIONAL_INTELLIGENCE: 'additionalIntelligence',
	MULTIPLIER_INTELLIGENCE: 'multiplierIntelligence',
	LIFE: 'life',
	ADDITIONAL_LIFE: 'additionalLife',
	MULTIPLIER_LIFE: 'multiplierLife',
	MANA: 'mana',
	ADDITIONAL_MANA: 'additionalMana',
	MULTIPLIER_MANA: 'multiplierMana',
	ENERGY_SHIELD: 'energyShield',
	ADDITIONAL_ENERGY_SHIELD: 'additionalEnergyShield',
	MULTIPLIER_ENERGY_SHIELD: 'multiplierEnergyShield',
	ARMOR: 'armor',
	ADDITIONAL_ARMOR: 'additionalArmor',
	MULTIPLIER_ARMOR: 'multiplierArmor',
	EVASION: 'evasion',
	ADDITIONAL_EVASION: 'additionalEvasion',
	MULTIPLIER_EVASION: 'multiplierEvasion',
	ACCURACY: 'accuracy',
	ADDITIONAL_ACCURACY: 'additionalAccuracy',
	MULTIPLIER_ACCURACY: 'multiplierAccuracy',
	PHYSICAL_DAMAGE_MIN: 'physicalDamageMin',
	ADDITIONAL_PHYSICAL_DAMAGE_MIN: 'additionalPhysicalDamageMin',
	MULTIPLIER_PHYSICAL_DAMAGE_MIN: 'multiplierPhysicalDamageMin',
	PHYSICAL_DAMAGE_MAX: 'physicalDamageMax',
	ADDITIONAL_PHYSICAL_DAMAGE_MAX: 'additionalPhysicalDamageMax',
	MULTIPLIER_PHYSICAL_DAMAGE_MAX: 'multiplierPhysicalDamageMax',
} as const;

export type PLAYER_STATS_TYPE_HELPER = (typeof PLAYER_STATS)[keyof typeof PLAYER_STATS];
